import { z } from "zod";

/** A single Lorebook/character_book entry, per the Character Card V2 spec. `.passthrough()`
 * keeps any vendor-specific fields (e.g. V3's `use_regex`, ST's own extras) intact through a
 * load -> edit -> save cycle even though this app doesn't render them yet. */
export const lorebookEntrySchema = z
  .object({
    keys: z.array(z.string()),
    content: z.string(),
    extensions: z.record(z.string(), z.unknown()).default({}),
    enabled: z.boolean(),
    insertion_order: z.number(),
    case_sensitive: z.boolean().optional(),
    name: z.string().optional(),
    priority: z.number().optional(),
    id: z.number().optional(),
    comment: z.string().optional(),
    selective: z.boolean().optional(),
    secondary_keys: z.array(z.string()).optional(),
    constant: z.boolean().optional(),
    position: z.enum(["before_char", "after_char"]).optional(),
  })
  .passthrough();

export const lorebookSchema = z
  .object({
    name: z.string().optional(),
    description: z.string().optional(),
    scan_depth: z.number().optional(),
    token_budget: z.number().optional(),
    recursive_scanning: z.boolean().optional(),
    extensions: z.record(z.string(), z.unknown()).default({}),
    entries: z.array(lorebookEntrySchema),
  })
  .passthrough();

export type LorebookEntry = z.infer<typeof lorebookEntrySchema>;
export type Lorebook = z.infer<typeof lorebookSchema>;

/** SillyTavern's numeric World Info positions; only 0/1 have a V2 equivalent. */
const ST_POSITION_TO_V2: Record<number, "before_char" | "after_char"> = { 0: "before_char", 1: "after_char" };

/** ST-named duplicates of V2 fields, dropped on import and regenerated by `toWorldInfo`. */
const ST_DUPLICATE_FIELDS = ["key", "keysecondary", "order", "disable", "uid", "displayIndex", "caseSensitive"];

/** Converts SillyTavern's native World Info export (as downloaded from e.g. Chub) into the
 * Character Card V2 `character_book` shape `lorebookSchema` expects. ST's format keys `entries`
 * by uid (`{"0": {...}}`) instead of using an array, names its fields `key`/`keysecondary`/
 * `order`/`disable`, and stores `position` as a number. Some exporters write both naming styles
 * side by side; existing V2 fields always win. Mirrors ST's own V2 conversion: positions other
 * than 0/1 (Author's Note, @depth, ...) fall back to `after_char`, with the original number kept
 * in `extensions.position` so SillyTavern restores it on re-import. Anything that's already a
 * V2 lorebook passes through untouched. */
export function normalizeWorldInfo(raw: unknown): unknown {
  if (!raw || typeof raw !== "object" || Array.isArray(raw)) return raw;
  const book = raw as Record<string, unknown>;
  const { entries } = book;
  if (!entries || typeof entries !== "object") return raw;

  const isStFormat = !Array.isArray(entries);
  const list = (isStFormat ? Object.values(entries) : (entries as unknown[])) as Record<string, unknown>[];
  if (isStFormat) {
    // Keep ST's on-screen order; plain object key order would sort uids numerically instead.
    list.sort((a, b) => Number(a.displayIndex ?? a.uid ?? 0) - Number(b.displayIndex ?? b.uid ?? 0));
  }

  const converted = list.map((entry) => {
    if (!entry || typeof entry !== "object") return entry;
    const out: Record<string, unknown> = { ...entry };
    out.keys ??= entry.key ?? [];
    out.content ??= "";
    out.enabled ??= entry.disable === undefined ? true : !entry.disable;
    out.insertion_order ??= entry.order ?? 0;
    if (out.secondary_keys === undefined && entry.keysecondary !== undefined) out.secondary_keys = entry.keysecondary;
    if (out.id === undefined && typeof entry.uid === "number") out.id = entry.uid;
    if (out.case_sensitive === undefined && typeof entry.caseSensitive === "boolean") out.case_sensitive = entry.caseSensitive;
    if (typeof entry.position === "number") {
      const extensions = { ...((entry.extensions as Record<string, unknown> | undefined) ?? {}) };
      extensions.position ??= entry.position;
      out.extensions = extensions;
      out.position = ST_POSITION_TO_V2[entry.position] ?? "after_char";
    }
    // The V2 names above are now the single source of truth while editing; ST's duplicates would
    // otherwise go stale after the first edit. `toWorldInfo` regenerates them on save.
    for (const stOnly of ST_DUPLICATE_FIELDS) delete out[stOnly];
    return out;
  });

  return { ...book, entries: converted };
}

/** Fields SillyTavern's own "new entry" template sets that have no V2 counterpart. Only used as
 * fallbacks — anything carried over from an imported file (via `.passthrough()`) wins. */
const ST_ENTRY_DEFAULTS = {
  selectiveLogic: 0,
  addMemo: true,
  excludeRecursion: false,
  probability: 100,
  useProbability: true,
  depth: 4,
  group: "",
};

/** Inverse of `normalizeWorldInfo`: writes a standalone lorebook in SillyTavern's World Info
 * format, so it can be imported straight into ST's World Info panel. Like the files Chub hands
 * out, every entry carries both naming styles (ST's `key`/`order`/`disable`/numeric `position`
 * plus V2's `keys`/`insertion_order`/`enabled`), so other tools reading either style keep working.
 * A non-V2 position remembered in `extensions.position` is kept as long as the V2 position the
 * user sees still maps to it; once they pick a different one in the editor, that choice wins. */
export function toWorldInfo(book: Lorebook): Record<string, unknown> {
  const entries: Record<string, unknown> = {};
  book.entries.forEach((entry, index) => {
    const v2Position = entry.position ?? "before_char";
    const remembered = entry.extensions?.position;
    const stPosition =
      typeof remembered === "number" && (ST_POSITION_TO_V2[remembered] ?? "after_char") === v2Position
        ? remembered
        : v2Position === "after_char"
          ? 1
          : 0;

    entries[String(index)] = {
      ...ST_ENTRY_DEFAULTS,
      ...entry,
      uid: index,
      id: index,
      displayIndex: index,
      key: entry.keys,
      keysecondary: entry.secondary_keys ?? [],
      secondary_keys: entry.secondary_keys ?? [],
      comment: entry.comment ?? "",
      constant: entry.constant ?? false,
      selective: entry.selective ?? false,
      order: entry.insertion_order,
      disable: !entry.enabled,
      ...(entry.case_sensitive !== undefined && { caseSensitive: entry.case_sensitive }),
      position: stPosition,
      extensions: { ...entry.extensions, position: stPosition },
    };
  });
  return { ...book, entries };
}
